name: rm_calculator
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_gallery_saver: ^2.0.3
  intl: ^0.18.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  screenshot: ^2.1.0
  share_plus: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
